$(document).ready(function(){
    $('.slider').slick({
        arrows:true,
        dots:false,
        adaptiveHeight:true,
        speed:1000,
        initialSlide:2,
        infinite:false,
    });
});